apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: resut-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: result-app
    image: kodecloud/examplevotingapp_result:v11
    ports:
      - containerPort: 80